on:
  push:
    paths:
      - '.github/**'
      - 'contracts/*.vy'
      - 'interface/*.js'
      - '!interface/run.js'
      - '!interface/script.js'
      - 'interface/*.json'
      - 'tests/*.py'
jobs:
  test:
    steps:
      - uses: actions/checkout@latest
      - uses: chill-viking/npm-ci@latest
        with:
          working-directory: './interface/'
      - uses: ApeWorX/github-action@latest
      - run: ape test --network=:local
